# Generated by Django 4.2.3 on 2023-08-14 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_lesson_5', '0004_alter_advertisement_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создание дата'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновление дата'),
        ),
    ]
